### PR TITLE
fix: support building on loongarch64 linux

### PR DESCRIPTION
**Pull request by zhangwenlong8911**
Signed-off-by: Wenlong Zhang <zhangwenlong@loongson.cn>

there is no dup2 on loong64.

### CODE REVIEW

**Comment by zhangwenlong8911** [comment]
image

i have already tested this on loong64 machines

**Comment by luke-belton** [comment]
Hey @zhangwenlong8911 - thanks for the PR! Unfortunately we won't be able to accept this as `loong64` is not an architecture that we support, and would be difficult for us to test against. We'd suggest forking this library in order to make the suggested changes.

You could also consider moving to [bugsnag/bugsnag-go@master/v2](https://github.com/bugsnag/bugsnag-go/tree/master/v2?rgh-link-date=2021-12-17T16%3A50%3A05Z) and use [bugsnag/panic-monitor](https://github.com/bugsnag/panic-monitor) which does not have a dependency on `dup2`. Bear in mind that this architecture is still not officially supported however.

**Comment by zhangwenlong8911** [comment]
Thank you for your review, loong64 have been support in [golang/sys](https://github.com/golang/sys)，and in project golang/sys, Dup2 is used as the package of Dup3 ，just like [syscall_linux.go](https://github.com/golang/sys/blob/87e55d71481061dc6dcfb9a4953c896af893c130/unix/syscall_linux.go) in golang/sys, Dup3 has been officially supported by golang on loong64

**Comment by zhangwenlong8911** [comment]
@luke-belton This repo is an important dependency of many go packages, please re-consider merging this.

**Pull request closed without merging**
