### PR TITLE
1.3.3 don't build on mac

### LINKED ISSUE #22: 1.3.3 don't build on mac
The `+build` filter logic on `dup2.go` should be:
```
not windows and not (linux and arm64)
```
But current meaning seems to be:
```
not windows and linux and (not arm64)
```

Maybe change it to:
```
// +build !windows
// +build !linux !arm64
```

### PR DESCRIPTION
**Pull request by yihuang**
Closes #22

fix the build tag

## Review

For the submitter, initial self-review:

- [ ] Commented on code changes inline explain the reasoning behind the approach
- [ ] Reviewed the test cases added for completeness and possible points for discussion
- [ ] A changelog entry was added for the goal of this pull request
- [ ] Check the scope of the changeset - is everything in the diff required for the pull request?
- This pull request is ready for:
  - [ ] Initial review of the intended approach, not yet feature complete
  - [ ] Structural review of the classes, functions, and properties modified
  - [ ] Final review

For the pull request reviewer(s), this changeset has been reviewed for:

- [ ] Consistency across platforms for structures or concepts added or modified
- [ ] Consistency between the changeset and the goal stated above
- [ ] Internal consistency with the rest of the library - is there any overlap between existing interfaces and any which have been added?
- [ ] Usage friction - is the proposed change in usage cumbersome or complicated?
- [ ] Performance and complexity - are there any cases of unexpected O(n^3) when iterating, recursing, flat mapping, etc?
- [ ] Concurrency concerns - if components are accessed asynchronously, what issues will arise
- [ ] Thoroughness of added tests and any missing edge cases
- [ ] Idiomatic use of the language

### CODE REVIEW

**Comment by pranitbauva1997** [comment]
@kattrali @mitchellh One of the libraries I am working with is dependent on this and I am running on Mac Catalina. Can you please help in review? If there is anything else needed, I would be very willing to contribute.

**Comment by pranitbauva1997** [comment]
@kattrali I am getting the same error which is supposedly fixed by this PR. Any ideas as to how I can fix those errors in another PR? Or can it be fixed in an another way?

While building this on Mac (amd64 arch), I get an error saying `dup2 is undefined`.

**Comment by kattrali** [comment]
Are you building with [v1.3.4](https://github.com/bugsnag/panicwrap/releases/tag/v1.3.4)?

**Comment by pranitbauva1997** [comment]
@kattrali Thanks for your quick responses. `v1.3.4` fixes the issue I was getting. Earlier I was working with `v1.3.3`.

**Comment by kattrali** [comment]
Great to hear! Feel free to open a new issue if anything else crops up.

**Comment by yihuang** [comment]
Works here too, just checked 👍

**Pull request closed without merging**
